x-django: &django
  build:
    context: .
    dockerfile: ./docker/django/Dockerfile
    args:
      ENVIRONMENT: production # Pass the build argument
  restart: always
  image: "${COMPOSE_PROJECT_NAME}_prod"
  depends_on:
    - postgres
    - redis
  volumes:
    - ./src:/opt/project/src:cached
    - ./data/prod:/data:z
    - static:/code/static/
    - attachments:/code/attachments/
  env_file:
    - ./.env

services:
  django:
    <<: *django
    command: prod
  celeryworker:
    <<: *django
    command: celery worker -l INFO
  celerybeat:
    <<: *django
    command: celery beat -l INFO
  flower:
    image: mher/flower:0.9.7
    command: "flower --broker=${REDIS_URL} --port=5555 --url-prefix=flower --basic_auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
    depends_on:
      - redis
    env_file:
      - ./.env
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: "${COMPOSE_PROJECT_NAME}_prod_postgres"
    restart: always
    volumes:
      - prod_postgres:/var/lib/postgresql/data:Z
      - prod_backups:/backups:z
    env_file:
      - ./.env
  redis:
    image: redis:6.0
    restart: always
  mkdocs:
    build:
      dockerfile: ./docker/mkdocs/Dockerfile
      context: ./
    env_file:
      - .env
    image: ${COMPOSE_PROJECT_NAME}/docs
    container_name: ${COMPOSE_PROJECT_NAME}-docs-${ENVIRONMENT}
    command:
      - build
    volumes:
      - ./docs:/code/docs
      - docs:/code/doc_site
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    image: "${COMPOSE_PROJECT_NAME}_prod_caddy"
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - prod_caddy:/data
      - static:/static
      - attachments:/attachments
      - docs:/docs
      - caddy_config:/config
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - ./.env
    depends_on:
      - django
      - flower

volumes:
  prod_postgres:
  prod_backups:
  prod_redis:
  prod_caddy:
  caddy_config:
  static:
  attachments:
  docs:
